[package]
name = "go-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1"

[dev-dependencies]
